### ISSUE TITLE
Some issues when loading all namespaces

### ISSUE THREAD

**Issue by vemv** [genmeblog/soundsynth#1]
Hi, lovely project!

I encountered a couple issues when firing up a repl and loading all namespaces (I have a custom setup which does that):

* merely `require`ing `sound.patch` plays+loops the associated song. It's nice to hear it but it gets old quickly. Probably it'd be better if the ns didn't have this compile-time side-effect.
* requiring `intro` spits the following stacktrace:

```clj
error {
 :cause javafx.event.EventHandler
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling at (cljfx/coerce.clj:1:1).
   :data #:clojure.error{:phase :compile-syntax-check, :line 1, :column 1, :source cljfx/coerce.clj}
   :at [clojure.lang.Compiler load Compiler.java 7648]}
  {:type java.lang.ClassNotFoundException
   :message javafx.event.EventHandler
   :at [java.net.URLClassLoader findClass URLClassLoader.java 382]}]
```

...I use AdoptOpenJDK. IIRC one needs Azul's or Oracle's JDK?

Thanks - V

**Comment by genmeblog** [comment]
`intro` is a file working with a https://github.com/scicloj/notespace/. Forget about it for a while. However it should work with OpenJDK15.

**Comment by genmeblog** [comment]
To start/stop song please call `sound.core/toggle-playing`. Treat this code as a demo 🙂

**Comment by vemv** [comment]
Thanks!

Nice pointer on JDK15, I didn't know it was a thing.

The thing with `sound.patch` and `intro` is that they can be automatically required by the repl or IDE. I think `cider-refresh` is a well-known example of auto-requiring solutions.

If it was possible to make ns loading less side-effectful that would be appreciated, else no issue!
